/**
 * SoundPackage — שלב 5.1: פורמט חבילת סאונד מקורי.
 *
 * פורמט JSON שמכיל את כל הידע המוזיקלי ש-PSY4 למד:
 * - metadata: גרסה, תאריך, סגנונות שזוהו
 * - voices: entries מ-sound bank (role, params, soundDNA, matchScore, reward)
 * - patterns: דפוסי kick/bass שנלמדו מהרדיו
 * - insights: BPM/scale/key שזוהו
 *
 * זה לא פורמט VSTi — זה פורמט שלנו, שמתאים למשפחת הכלים ב-GitHub.
 * ניתן לייצא, לשתף, ולטעון חזרה.
 */

import { SoundBank, type SoundBankEntry } from './soundBank';
import { type OnsetRole } from './onsetAnalyzer';

export interface SoundPackageMetadata {
  format: 'psy4-sound-package';
  version: string;
  createdAt: number;
  createdBy: string;
  detectedStyles: string[];
  totalEntries: number;
  totalPatterns: number;
  sourceRadioStations: string[];
  notes: string;
}

export interface PackageVoice {
  id: string;
  role: OnsetRole;
  voiceParams: Record<string, number>;
  matchScore: number;
  reward: number;
  usageCount: number;
  sourceStyle: string;
  soundDNASummary: {
    brightness: number;
    subEnergy: number;
    midEnergy: number;
    highEnergy: number;
    transientSharpness: number;
  };
}

export interface PackagePattern {
  role: OnsetRole;
  pattern: number[];      // 16 steps, 0..1
  bpm: number;
  confidence: number;
  sourceStyle: string;
}

export interface PackageInsights {
  bpm: number;
  bpmConfidence: number;
  rootPc: number;
  scaleName: string;
  scaleMatchScore: number;
}

export interface SoundPackage {
  metadata: SoundPackageMetadata;
  voices: PackageVoice[];
  patterns: PackagePattern[];
  insights: PackageInsights;
}

const PACKAGE_VERSION = '1.0.0';

export class PackageExporter {
  private bank: SoundBank;

  constructor(bank: SoundBank) {
    this.bank = bank;
  }

  /**
   * מייצא חבילת סאונד מלאה מה-bank הנוכחי.
   */
  async export(
    detectedStyles: string[],
    sourceStations: string[],
    insights: PackageInsights,
    patterns: PackagePattern[],
  ): Promise<SoundPackage> {
    // אסוף את כל ה-entries מכל ה-roles
    const roles: OnsetRole[] = ['kick', 'bass', 'lead', 'hat', 'perc'];
    const allEntries: SoundBankEntry[] = [];
    for (const role of roles) {
      const entries = await this.bank.all(role);
      allEntries.push(...entries);
    }

    // המר לפורמט חבילה
    const voices: PackageVoice[] = allEntries.map(e => ({
      id: e.id,
      role: e.role,
      voiceParams: e.voiceParams || {},
      matchScore: e.matchScore,
      reward: e.reward,
      usageCount: e.usageCount,
      sourceStyle: e.sourceStyle,
      soundDNASummary: {
        brightness: e.soundDNA.brightness,
        subEnergy: e.soundDNA.subEnergy,
        midEnergy: e.soundDNA.midEnergy,
        highEnergy: e.soundDNA.highEnergy,
        transientSharpness: e.soundDNA.transientSharpness,
      },
    }));

    const pkg: SoundPackage = {
      metadata: {
        format: 'psy4-sound-package',
        version: PACKAGE_VERSION,
        createdAt: Date.now(),
        createdBy: 'PSY4 Engine',
        detectedStyles: detectedStyles.length > 0 ? detectedStyles : ['unknown'],
        totalEntries: voices.length,
        totalPatterns: patterns.length,
        sourceRadioStations: sourceStations,
        notes: 'Generated by PSY4 self-learning engine',
      },
      voices,
      patterns,
      insights,
    };

    console.log(`[PSY4] שלב 5.1 PackageExporter: exported ${voices.length} voices, ${patterns.length} patterns`);
    return pkg;
  }

  /**
   * מייצא חבילה כ-JSON string (להורדה).
   */
  async exportJSON(
    detectedStyles: string[],
    sourceStations: string[],
    insights: PackageInsights,
    patterns: PackagePattern[],
  ): Promise<string> {
    const pkg = await this.export(detectedStyles, sourceStations, insights, patterns);
    return JSON.stringify(pkg, null, 2);
  }

  /**
   * מוריד קובץ JSON למשתמש.
   */
  async download(
    detectedStyles: string[],
    sourceStations: string[],
    insights: PackageInsights,
    patterns: PackagePattern[],
  ): Promise<void> {
    const json = await this.exportJSON(detectedStyles, sourceStations, insights, patterns);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `psy4-package-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    console.log('[PSY4] שלב 5.1 Package downloaded');
  }
}

export class PackageImporter {
  private bank: SoundBank;

  constructor(bank: SoundBank) {
    this.bank = bank;
  }

  /**
   * טוען חבילה מ-JSON string.
   * ממלא את ה-sound bank עם ה-entries מהחבילה.
   */
  async importJSON(jsonString: string): Promise<SoundPackage> {
    const pkg = JSON.parse(jsonString) as SoundPackage;
    if (pkg.metadata.format !== 'psy4-sound-package') {
      throw new Error('Invalid package format — expected psy4-sound-package');
    }

    // נקה את ה-bank הנוכחי לפני טעינה
    await this.bank.clearAll();

    // טען כל entry
    let imported = 0;
    for (const voice of pkg.voices) {
      // בנה SoundDNA מלא מה-summary (שאר השדות יהיו defaults)
      const soundDNA = {
        role: 'fx' as const,
        brightness: voice.soundDNASummary.brightness,
        harmonicity: 0.5,
        noisiness: 0.3,
        spectralSlope: -0.5,
        roughness: 0.2,
        subEnergy: voice.soundDNASummary.subEnergy,
        bodyEnergy: voice.soundDNASummary.subEnergy * 0.7,
        midEnergy: voice.soundDNASummary.midEnergy,
        highEnergy: voice.soundDNASummary.highEnergy,
        transientSharpness: voice.soundDNASummary.transientSharpness,
        attackTime: 0.005,
        decayTime: 0.2,
        sustainLevel: 0.2,
        releaseTime: 0.1,
        saturation: 0.4,
        distortionCharacter: 0.3,
        filterCutoff: 0,
        filterResonance: 0,
        filterType: 'lowpass' as const,
        filterEnvelopeAmount: 0.3,
        pitchModulation: 0,
        fmAmount: 0,
        detune: 0,
        stereoWidth: 0,
        stereoMotion: 0,
        confidence: voice.matchScore,
        usageCount: voice.usageCount,
        reward: voice.reward,
        sourceStyle: voice.sourceStyle,
        sourceContext: 'imported',
      };

      // בנה recipe מינימלי
      const recipe = {
        oscType: 'sawtooth' as OscillatorType,
        oscLayers: 1,
        detune: 0,
        fmAmount: 0,
        filterType: 'lowpass' as BiquadFilterType,
        filterCutoff: voice.voiceParams.cutoffStart ?? 800,
        filterResonance: 1,
        filterEnvAmount: 0.5,
        attackTime: 0.001,
        decayTime: voice.voiceParams.subDecay ?? 0.2,
        sustainLevel: 0.3,
        releaseTime: 0.1,
        saturationAmount: voice.voiceParams.saturation ?? 0.4,
        stereoWidth: 0,
        subLevel: voice.voiceParams.subLevel ?? 0.45,
        bodyLevel: voice.voiceParams.subLevel ?? 0.45,
        harmonicLevel: voice.voiceParams.harmonicLevel ?? 0.55,
      };

      await this.bank.add(
        voice.role,
        soundDNA,
        recipe,
        voice.matchScore,
        voice.sourceStyle,
        voice.voiceParams,
      );
      imported++;
    }

    console.log(`[PSY4] שלב 5.1 PackageImporter: imported ${imported} voices from package`);
    return pkg;
  }

  /**
   * קורא קובץ מ-file input.
   */
  async importFromFile(file: File): Promise<SoundPackage> {
    const text = await file.text();
    return this.importJSON(text);
  }
}
