/**
 * MotifMemory — stores and transforms musical motifs.
 *
 * F5 RULE 4-5: Motifs are not single notes — they are pitch contours with
 * rhythm, register, and phrase context. The memory tracks:
 * - motifs extracted from radio pitch observations
 * - motifs generated by the composition planner
 * - transformations applied (transpose, invert, retrograde, fragment)
 * - usage count and recency (anti-repetition)
 *
 * The transformation engine uses psy-foundation's motif operators.
 */

import { type MotifNote, generateMotif, transpose, invert, fragment, retrograde, vary } from './primitives/motif';
import { type Scale, degreeToMidi, stableDegrees } from './primitives/scales';
import { Rng } from './primitives/rng';

export type MotifTransformType = 'none' | 'transpose' | 'invert' | 'retrograde' | 'fragment' | 'vary';

export interface StoredMotif {
  readonly id: string;
  readonly notes: MotifNote[];
  readonly source: 'radio' | 'generated' | 'seed';
  readonly transform: MotifTransformType;
  readonly rootPc: number;
  readonly scaleName: string;
  readonly createdAt: number; // bar index when created
  readonly usageCount: number;
  readonly lastUsedBar: number;
  readonly confidence: number;
}

export interface MotifMemorySnapshot {
  readonly motifCount: number;
  readonly motifs: StoredMotif[];
  readonly lastTransform: MotifTransformType;
  readonly lastMotifId: string | null;
}

const MAX_MOTIFS = 32;

export class MotifMemory {
  private motifs: StoredMotif[] = [];
  private nextId = 0;
  private lastTransform: MotifTransformType = 'none';
  private lastMotifId: string | null = null;
  private rng: Rng;

  constructor(seed: number = 42) {
    this.rng = new Rng(seed);
  }

  /**
   * Generate a new motif from the current musical context.
   */
  generateMotif(
    rootPc: number,
    scale: Scale,
    scaleName: string,
    bar: number,
    density: number,
    novelty: number,
  ): StoredMotif {
    // Use novelty to influence generation parameters
    const seed = this.rng.int(1, 100000);
    const steps = 32; // 2 bars of 16th notes
    const motifDensity = Math.max(0.3, Math.min(0.9, density + (novelty - 0.5) * 0.3));

    const notes = generateMotif(rootPc, scale, {
      seed,
      steps,
      density: motifDensity,
      glideProb: 0.3 + novelty * 0.3,
      responseShift: this.rng.int(1, 3),
    });

    const motif: StoredMotif = {
      id: `motif-${this.nextId++}`,
      notes,
      source: 'generated',
      transform: 'none',
      rootPc,
      scaleName,
      createdAt: bar,
      usageCount: 0,
      lastUsedBar: -1,
      confidence: 0.5,
    };

    this.add(motif);
    this.lastMotifId = motif.id;
    this.lastTransform = 'none';
    return motif;
  }

  /**
   * Transform an existing motif. Returns a NEW motif (does not modify the original).
   * F5 RULE 5: Transformations are musical, not random.
   */
  transformMotif(
    motif: StoredMotif,
    transformType: MotifTransformType,
    rootPc: number,
    scale: Scale,
    bar: number,
  ): StoredMotif {
    let notes: MotifNote[];
    let actualTransform = transformType;

    switch (transformType) {
      case 'transpose':
        // Transpose by 1-3 scale degrees (musical, not random)
        const degrees = this.rng.int(1, 3) * (this.rng.next() > 0.5 ? 1 : -1);
        notes = transpose(motif.notes, rootPc, scale, degrees);
        break;
      case 'invert':
        notes = invert(motif.notes, rootPc, scale);
        break;
      case 'retrograde':
        notes = retrograde(motif.notes);
        break;
      case 'fragment':
        // Keep first 60-80% of notes
        const count = Math.max(2, Math.floor(motif.notes.length * (0.6 + this.rng.next() * 0.2)));
        notes = fragment(motif.notes, count);
        break;
      case 'vary':
        notes = vary(motif.notes, rootPc, scale, 'transpose', this.rng.int(1, 2));
        break;
      default:
        notes = [...motif.notes];
        actualTransform = 'none';
    }

    const transformed: StoredMotif = {
      id: `motif-${this.nextId++}`,
      notes,
      source: motif.source,
      transform: actualTransform,
      rootPc,
      scaleName: motif.scaleName,
      createdAt: bar,
      usageCount: 0,
      lastUsedBar: -1,
      confidence: motif.confidence * 0.9, // slightly less confident than original
    };

    this.add(transformed);
    this.lastMotifId = transformed.id;
    this.lastTransform = actualTransform;
    return transformed;
  }

  /**
   * Pick the best motif for the current context.
   * Considers: recency (anti-repetition), confidence, novelty budget.
   */
  pickMotif(bar: number, novelty: number): StoredMotif | null {
    if (this.motifs.length === 0) return null;

    // Score each motif: prefer recent but not TOO recent (anti-repetition)
    const scored = this.motifs.map(m => {
      const barsSinceUse = bar - m.lastUsedBar;
      const recencyPenalty = barsSinceUse < 4 ? 0.3 : 0; // penalize motifs used in last 4 bars
      const confidenceBonus = m.confidence * 0.3;
      const noveltyBonus = m.transform !== 'none' ? novelty * 0.2 : 0;
      return { motif: m, score: confidenceBonus + noveltyBonus - recencyPenalty + this.rng.next() * 0.1 };
    });

    scored.sort((a, b) => b.score - a.score);
    const picked = scored[0].motif;

    // Mark as used
    const idx = this.motifs.indexOf(picked);
    this.motifs[idx] = { ...picked, usageCount: picked.usageCount + 1, lastUsedBar: bar };

    return this.motifs[idx];
  }

  /**
   * Decide whether to transform the current motif or generate a new one.
   * Based on novelty budget and phrase position.
   */
  shouldTransform(novelty: number, barsSinceLastTransform: number): boolean {
    // Transform more often when novelty is high
    const threshold = 0.3 + (1 - novelty) * 0.5;
    return barsSinceLastTransform >= 2 && this.rng.next() > threshold;
  }

  /**
   * Should we generate a completely new motif?
   */
  shouldGenerateNew(novelty: number, barsSinceLastNew: number): boolean {
    if (barsSinceLastNew >= 8) return true; // force new every 8 bars
    return this.rng.next() < novelty * 0.15;
  }

  /**
   * Choose which transformation to apply.
   */
  chooseTransform(): MotifTransformType {
    const r = this.rng.next();
    if (r < 0.3) return 'transpose';
    if (r < 0.5) return 'invert';
    if (r < 0.7) return 'fragment';
    if (r < 0.85) return 'retrograde';
    return 'vary';
  }

  private add(motif: StoredMotif): void {
    this.motifs.push(motif);
    if (this.motifs.length > MAX_MOTIFS) {
      // Remove oldest, least-used motifs
      this.motifs.sort((a, b) => b.usageCount - a.usageCount);
      this.motifs = this.motifs.slice(0, MAX_MOTIFS);
    }
  }

  snapshot(): MotifMemorySnapshot {
    return {
      motifCount: this.motifs.length,
      motifs: [...this.motifs],
      lastTransform: this.lastTransform,
      lastMotifId: this.lastMotifId,
    };
  }

  reset(): void {
    this.motifs = [];
    this.nextId = 0;
    this.lastTransform = 'none';
    this.lastMotifId = null;
    this.rng = new Rng(42);
  }
}
